version: "3.8"

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting node_modules
    command: ["node", "index.js"]
